# Generated by Django 5.0.7 on 2024-09-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepdf',
            name='disc',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='filepdf',
            name='file',
            field=models.FileField(default='', upload_to='filePDF/'),
        ),
        migrations.AlterField(
            model_name='filepdf',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
