# Generated by Django 5.0.7 on 2024-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filepdf_disc_alter_filepdf_file_alter_filepdf_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepdf',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
